name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      - "react-microfe/container/**"

defaults:
  run:
    working-directory: react-microfe/container

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: binhhc86/action-aws-cli@v1.1
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}